# -*- coding: utf-8 -*-
"""Week2_Assesment_Kiruthick.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xXPJtBqnVq7zyk_0_XXCMB63CahMaI2l

Section - A

Q1.

A Series is essentially a single column of data with an index, whereas a DataFrame is a 2D table composed of multiple aligned Series sharing the same index. You can use .head() on both to preview data, but an operation like dropping a column via .drop(columns=[...]) is exclusive to DataFrames since a Series doesn't have multiple columns to drop from.

Q2.

Setting inplace=True modifies the existing object directly in memory instead of creating a new copy. The pandas team is phasing it out because it doesn't actually save memory, breaks the ability to chain methods together, and frequently causes hidden SettingWithCopyWarning bugs. I’d avoid it in common steps like df.dropna(inplace=True), opting for direct re-assignment (df = df.dropna()) instead.

Q3.

.fillna() swaps out missing values (NaN) with a fallback value you choose, while .dropna() just throws away the rows or columns containing those missing values. You’d use .fillna() when dropping rows ruins your dataset size, like filling missing customer age values with the median. You’d pick .dropna() when the missing data is critical and can’t be guessed, like dropping transactions where the customer_id or amount is completely blank.

Q4.

Plain pd.to_numeric(col) will immediately crash your script if it hits a single non-numeric piece of text (like "Undisclosed" or "N/A"). Adding errors='coerce' tells pandas to gracefully convert those unparseable strings into NaN flags instead of failing. On messy real-world data, you almost always need errors='coerce' so your data pipeline doesn't break over typos or text entries in currency columns.

Q5.

.loc selects data using row and column labels, while .iloc looks strictly at integer positions (0-indexed). For example, df.loc['User_A'] finds the row labeled "User_A", while df.iloc[0] grabs whatever row is sitting at the very top of the table. If you sort your data using df.sort_values(), the physical rows move but retain their original index labels; at that point, df.iloc[0] fetches the new top row, while df.loc[0] looks for the specific row that originally had the number 0 as its label.

Q6.

.map() is best for transforming every element using a dictionary look-up or a simple function.

.apply() handles more complex, custom logic across elements via a lambda or a python function.

.replace() is optimized for swapping out specific exact values without touching the rest of the series. Reach for .replace() to swap out specific typo strings, .map() for key-value dictionary translations, and .apply() for complex math operations.

Q7.

It's a warning pandas throws when you try to modify data on a slice of a DataFrame, because it's ambiguous whether you are changing the original dataset or a temporary copy in memory.

Triggers it: df_filtered = df[df['rating'] > 4] followed by df_filtered['rating'] = 5 (chained assignment).

The Fix: Explicitly create an isolated copy when slicing the dataframe by adding .copy(), like: df_filtered = df[df['rating'] > 4].copy().

Q8.

pd.cut() sets up bins based on equal-width ranges (e.g., dividing an income scale into 0−$50k,$50k−$100k,$100k+), whereas pd.qcut() sets up bins based on sample quantiles to ensure the exact same number of people end up in each bucket. For income tiers, pd.cut() fits much better because economic classes are defined by specific income thresholds, not by forcing exactly 33% of your customers into a "High Earners" group regardless of what they actually make.

Section - B

Q9
"""

# Predicted Output:
#     a  b
# 0  10  4
# 1  20  5
# 2  30  6
# Explanation: df2 = df creates a reference to the same memory object. Modifying df2 changes df.

import pandas as pd
df = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6]})
df2 = df
df2['a'] = [10, 20, 30]
print(df)

"""Q10."""

# Predicted Output:
# 3.0
# 12.0
# Explanation: Pandas statistical functions skip NaN values by default.

import pandas as pd
import numpy as np
s = pd.Series([1, 2, np.nan, 4, 5])
print(s.mean())
print(s.sum())

# Predicted Output:
# float64
# 700.0
# Explanation: 'NA' is coerced into np.nan which forces the integer column to float precision.

import pandas as pd
df = pd.DataFrame({'price': ['100', '200', 'NA', '400']})
df['price'] = pd.to_numeric(df['price'], errors='coerce')
print(df['price'].dtype)
print(df['price'].sum())

"""Q11"""

# Predicted Output:
# float64
# 700.0
# Explanation: 'NA' is coerced into np.nan which forces the integer column to float precision.

import pandas as pd
df = pd.DataFrame({'price': ['100', '200', 'NA', '400']})
df['price'] = pd.to_numeric(df['price'], errors='coerce')
print(df['price'].dtype)
print(df['price'].sum())

"""Q12"""

# Predicted Output:
# name    Rahul
# age        22
# Name: 0, dtype: object
# <class 'pandas.core.series.Series'>
# Explanation: Selecting a single row out of a DataFrame yields a Pandas Series object.

import pandas as pd
df = pd.DataFrame({'name': ['Rahul', 'Priya'], 'age': [22, 21]})
print(df.loc[0])
print(type(df.loc[0]))

"""Q13"""

# Predicted Output:
#    rating
# 0     4.5
# 1     3.8
# 2     4.2
# 3     5.0
#    rating
# 0     9.0
# 2     8.4
# 3    10.0
# Explanation: A SettingWithCopyWarning is raised because df_filtered was assigned from a sliced subset.

import pandas as pd
df = pd.DataFrame({'rating': [4.5, 3.8, 4.2, 5.0]})
df_filtered = df[df['rating'] > 4]
df_filtered['rating'] = df_filtered['rating'] * 2
print(df)
print(df_filtered)

"""Q14"""

# Predicted Output:
# 0    small
# 1    small
# 2        9
# 3       16
# Name: a, dtype: object
# Explanation: Mixing strings ('small') and integers/floats sets the overall pandas dtype to object.

import pandas as pd
df = pd.DataFrame({'a': [1, 2, 3, 4]})
result = df['a'].apply(lambda x: x**2 if x > 2 else 'small')
print(result)
print(result.dtype)

"""Q15"""

# Predicted Output:
# 3
# 4
# Delhi        2
# Mumbai       1
# Bengaluru    1
# Name: city, dtype: int64
# Explanation: nunique() excludes NaN. unique() includes NaN, increasing len. value_counts() excludes NaN.

import pandas as pd
df = pd.DataFrame({'city': ['Delhi', 'Mumbai', 'Delhi', 'Bengaluru', None]})
print(df['city'].nunique())
print(len(df['city'].unique()))
print(df['city'].value_counts())

"""Q16"""

# Predicted Output:
#    a   b
# 1  2  20
# 2  3  30
#    a   b
# 2  3  30
# Explanation: The middle commented line fails because bitwise operations (&) demand parenthesized criteria to resolve operator precedence correctly.

import pandas as pd
df = pd.DataFrame({'a': [1, 2, 3], 'b': [10, 20, 30]})
print(df[df['a'] > 1])
# print(df[df['a'] > 1 & df['b'] > 15])  # Throws ValueError/TypeError
print(df[(df['a'] > 1) & (df['b'] > 15)])

"""Section - C"""

import pandas as pd
import numpy as np

# Load the raw dataset
df_raw = pd.read_csv("indian_startups_fundingDADS.csv")

# Create copy for manipulation
df = df_raw.copy()

# 1. Rename columns to clean snake_case
df.columns = ['startup_name', 'city', 'industry', 'funding_stage', 'amount', 'funding_date', 'investors', 'founded_year']

# 2. Clean startup_name and city - strip whitespace, title case
df['startup_name'] = df['startup_name'].astype(str).str.strip().str.title()
df['city'] = df['city'].astype(str).str.strip().str.title()

# 3. Standardise city aliases
city_mapping = {
    'Bangalore': 'Bengaluru', 'Blr': 'Bengaluru',
    'Bombay': 'Mumbai',
    'Gurgaon': 'Gurugram',
    'Delhi': 'New Delhi',
    'Calcutta': 'Kolkata',
    'Madras': 'Chennai'
}
df['city'] = df['city'].replace(city_mapping)

# 4. Standardise industry and funding_stage variants using dicts
industry_mapping = {
    'E-Commerce': 'Ecommerce', 'Ecommerce': 'Ecommerce', 'E-commerce': 'Ecommerce',
    'Fin-Tech': 'Fintech', 'Fintech': 'Fintech',
    'Ed-Tech': 'Edtech', 'Edtech': 'Edtech',
    'Health-Tech': 'Health Tech', 'Healthtech': 'Health Tech', 'Health Tech': 'Health Tech'
}
df['industry'] = df['industry'].replace(industry_mapping)

stage_mapping = {
    'Seed Round': 'Seed', 'Seed Funding': 'Seed',
    'Series A1': 'Series A', 'Series A': 'Series A',
    'Pre Series A': 'Pre-Series A', 'Pre-Series A': 'Pre-Series A'
}
df['funding_stage'] = df['funding_stage'].replace(stage_mapping)

# 5. Convert amount to numeric (in INR Cr) without forbidden libraries (No regex used)
def clean_amount(val):
    if pd.isna(val):
        return np.nan
    val_str = str(val).replace(',', '').strip()
    if 'Undisclosed' in val_str or val_str == '' or val_str == 'nan':
        return np.nan

    # Check prefixes/suffixes and strip units
    val_str = val_str.replace('INR', '').replace('Cr', '').replace('Crore', '').strip()
    try:
        return float(val_str)
    except:
        return np.nan

df['amount'] = df['amount'].apply(clean_amount)

# 6. Convert funding_date to datetime
df['funding_date'] = pd.to_datetime(df['funding_date'], errors='coerce', dayfirst=True)

# 7. Drop duplicate rows
df = df.drop_duplicates().reset_index(drop=True)

"""Q17"""

print("(a) Rows and columns:", df_raw.shape)
print("(b) Missing values per column:\n", df_raw.isnull().sum())
print("(c) Exact duplicate rows:", df_raw.duplicated().sum())

"""Q18"""

sorted_cols = sorted(list(df.columns))
print(sorted_cols)

"""Q19

"""

founded_clean = df['founded_year'].dropna()
stats_dict = {
    'count': int(founded_clean.count()),
    'mean': float(founded_clean.mean()),
    'min': float(founded_clean.min()),
    'max': float(founded_clean.max()),
    'median': float(founded_clean.median()),
    'std': float(founded_clean.std())
}
print(stats_dict)

"""Q20"""

unique_cities = sorted(df['city'].dropna().unique())
print("Unique Cities List:", unique_cities)
print("Count of Unique Cities:", len(unique_cities))

"""Q21"""

print(df['industry'].value_counts())

"""Q22"""

print("(a) Dtype:", df['amount'].dtype)
print("(b) NaN count (from Undisclosed entries):", df['amount'].isna().sum())
print("(c) Mean funding amount:", df['amount'].mean())
print("(d) Min amount:", df['amount'].min(), "| Max amount:", df['amount'].max())

"""Q23"""

deals_per_year = df['funding_date'].dt.year.value_counts()
print("(a) Deals per year:\n", deals_per_year)
print("(b) Year with highest deals:", deals_per_year.idxmax())

"""Q24"""

print(df['funding_stage'].value_counts())

"""Q25"""

blr_large = df[(df['city'] == 'Bengaluru') & (df['amount'] > 100)].sort_values(by='amount', ascending=False)
print(blr_large[['startup_name', 'amount']])

"""Q26"""

target_industries = ['Fintech', 'Edtech', 'Health Tech']
count_target = df[df['industry'].isin(target_industries)].shape[0]
print("Total count:", count_target)

"""Q27"""

founded_between = df[df['founded_year'].between(2015, 2020)].shape[0]
print("Startups founded between 2015 and 2020 inclusive:", founded_between)

"""Q28

"""

pay_startups = df[df['startup_name'].str.contains('pay', case=False, na=False)]['startup_name'].unique()
print(pay_startups)

"""Q29"""

df['funding_efficiency'] = df['amount'] / (2024 - df['founded_year'])
top_10_efficient = df.sort_values(by='funding_efficiency', ascending=False).head(10)
print(top_10_efficient[['startup_name', 'industry', 'amount', 'founded_year', 'funding_efficiency']])

"""Q30"""

def get_tier(amt):
    if pd.isna(amt):
        return 'Small / Unknown'
    elif amt >= 1000:
        return 'Unicorn'
    elif amt >= 500:
        return 'Mega'
    elif amt >= 100:
        return 'Large'
    elif amt >= 10:
        return 'Mid'
    else:
        return 'Small / Unknown'

df['funding_tier'] = df['amount'].apply(get_tier)
print(df['funding_tier'].value_counts())

"""Q31"""

# Using manual bin assignments matching pd.cut criteria boundary logic safely
df['era'] = pd.cut(df['founded_year'], bins=[-np.inf, 2009, 2017, np.inf], labels=['Early', 'Growth', 'Recent'])
print(df['era'].value_counts())

"""Q32"""

df['investor_count'] = df['investors'].apply(lambda x: len(str(x).split(', ')) if pd.notna(x) and str(x) != 'nan' else 0)
print(df['investor_count'].value_counts())

"""Q33"""

avg_funding_industry = df.groupby('industry')['amount'].mean().sort_values(ascending=False)
print(avg_funding_industry.head(5))

"""Q34"""

city_summary = df.groupby('city').agg(
    startup_count=('startup_name', 'count'),
    total_funding=('amount', 'sum'),
    avg_funding=('amount', 'mean')
)
print(city_summary.sort_values(by='startup_count', ascending=False).head(10))

"""Q35"""

ind_group = df.groupby('industry').agg(
    startup_count=('startup_name', 'count'),
    avg_funding=('amount', 'mean')
)
filtered_industries = ind_group[ind_group['startup_count'] >= 15]
highest_dense_industry = filtered_industries.sort_values(by='avg_funding', ascending=False).head(1)

"""Q36"""

top_5_industries = df['industry'].value_counts().head(5).index
df_top_ind = df[df['industry'].isin(top_5_industries)]
cross_tab = pd.crosstab(df_top_ind['industry'], df_top_ind['funding_tier'])
print(cross_tab)

"""Q37"""

# Drop missing amounts to avoid incorrect idxmax metrics
df_amount_clean = df.dropna(subset=['amount'])
idx_max = df_amount_clean.groupby('industry')['amount'].idxmax()
highest_funded_per_ind = df_amount_clean.loc[idx_max, ['startup_name', 'industry', 'city', 'amount']]
print(highest_funded_per_ind)

"""Q38"""

emerging_players = df[
    (df['founded_year'] >= 2019) &
    (df['amount'] >= 100) &
    (df['industry'].isin(['Fintech', 'Edtech', 'Health Tech']))
].sort_values(by='amount', ascending=False)

print(emerging_players[['startup_name', 'industry', 'city', 'founded_year', 'amount']])

# Analysis insight comment:
# A VC analyst cares deeply about this list because it identifies young market disruptors that
# have achieved massive capital traction very rapidly, representing strong growth-signals.

"""Q39"""

city_hubs = df.groupby('city').agg(
    startup_count=('startup_name', 'count'),
    total_funding=('amount', 'sum')
)
filtered_hubs = city_hubs[city_hubs['startup_count'] >= 20].sort_values(by='total_funding', ascending=False)
print(filtered_hubs)

"""Q40"""

saturation = df.groupby(['city', 'industry']).size().sort_values(ascending=False)
print("Top 10 Most-Saturated Combinations:\n", saturation.head(10))